Some organization changes
Galzai/MK32 pull request #31
Opened 2021-07-05 20:32 UTC by dungphan90

- Updated to ESP-IDF v4.4.
- Migrated to CMake build system.
- Adding Docker to avoid dependency mess.
- Developed "CatiONE OLKB" that relies on this firmware (https://github.com/dungphan90/OLKBBLE.git, don't judge me yet, I will clean up this codebase "soon"). Notice the change in the keyboard matrix and the GPIO connections.

2021-07-06 16:55 UTC, Galzai requested changes
Nice clean-up work, and thanks for setting a docker container!

2021-07-06 16:55 UTC, Galzai commented on build.sh
> +#!/usr/bin/zsh
maybe better if it was '#!/bin/bash' since zsh does not come pre-packaged with every distro

2021-07-06 16:55 UTC, Galzai commented on run.sh
> +#!/usr/bin/zsh
maybe better if it was '#!/bin/bash' since zsh does not come pre-packaged with every distro

2021-07-06 16:55 UTC, Galzai commented on README.md
>  Note: Currently tested and working on esp-idf v4.0.
This can be removed now

2021-07-06 17:18 UTC, Semphora commented
i'm confused. this looks like a mix off quality of live changes (docker, cmake etc.) and a specific project in "OLKB BLE (Planlk-like). c7bbbc4"? why is the latter part of a pull request? am i missing something?

2021-07-06 20:14 UTC, dungphan90 commented
> i'm confused. this looks like a mix off quality of live changes (docker, cmake etc.) and a specific project in "OLKB BLE (Planlk-like). [c7bbbc4](https://github.com/Galzai/MK32/commit/c7bbbc417743df6c7a045066cc1f1f9c25f8dc1a)"? why is the latter part of a pull request? am i missing something?

So, sorry, you're right. I made some mess there. I want to keep Gal's default keymap layout/matrix setup and have my keyboard's layout/matrix moved to a new branch. I will roll back the changes in the keyboard setup make a separate pull request for the QOL part.

2021-07-07 04:27 UTC, Galzai commented
Closing PR (Will merge seperate PR with only QOL changes)

2021-07-07 04:27 UTC, closed without merging